// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function($) {
    return function($el, msg, type, dismissible) {
      var $button;
      if (type == null) {
        type = 'info';
      }
      if (dismissible == null) {
        dismissible = true;
      }
      $el.addClass("alert-" + type).html(msg);
      if (dismissible) {
        $button = $("<button type='button' class='close'>&times;</button>").click(function() {
          return $el.hide();
        });
        $el.addClass("alert-dismissable").prepend($button);
      }
      $el.show();
      return $el;
    };
  });

}).call(this);
