// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: 'js',
    paths: {
      lib: '../bower_components',
      jquery: '../bower_components/jquery/jquery',
      handsontable: '../bower_components/handsontable/dist/jquery.handsontable.full',
      csvparse: '../bower_components/jquery-csv/src/jquery.csv',
      FileSaver: '../bower_components/FileSaver/FileSaver',
      bootstrap: '../bower_components/bootstrap/dist/js/bootstrap.min'
    },
    shim: {
      csvparse: {
        deps: ['jquery']
      },
      handsontable: {
        deps: ['jquery']
      },
      FileSaver: {
        exports: 'saveAs'
      },
      bootstrap: {
        deps: ['jquery']
      }
    }
  });

  require(['jquery', 'FileSaver', 'file/setupFileUpload', 'file/setupRemoteFileLoad', 'csv/table2csv', 'csv/csv2table', 'alert', 'bootstrap'], function($, saveAs, setupFileUpload, setupRemoteFileLoad, table2csv, csv2table, alert) {
    var $tablediv;
    $tablediv = $("#test-div");
    $tablediv.hide();
    setupFileUpload($('#localUploadModal .loadFile'), $('#files'), $tablediv);
    setupFileUpload($('#localUploadModal .appendFile'), $('#files'), $tablediv, true);
    setupRemoteFileLoad($('#remoteUploadModal .loadFile'), $tablediv);
    setupRemoteFileLoad($('#remoteUploadModal .appendFile'), $tablediv, true);
    csv2table("volume_id, class\n , ");
    return $(".download-csv").bind("click", function(e) {
      var blob, csvdata;
      csvdata = table2csv($tablediv);
      if (csvdata) {
        blob = new Blob([csvdata], {
          type: "text/csv;charset=utf-8"
        });
        return saveAs(blob, 'workset.csv');
      } else {
        return alert($(".alert"), "No data to export!", "danger");
      }
    });
  });

}).call(this);
