// Generated by CoffeeScript 1.6.3
(function() {
  define(['file/loadRemoteFile'], function(loadRemoteFile) {
    return function($el) {
      $el.text("test");
      return $el.bind('change', loadRemoteFile);
    };
  });

}).call(this);
