// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var escapeRow;
    escapeRow = function(arr) {
      return arr.join(', ');
    };
    return function(arrs) {
      var arr;
      arrs = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arrs.length; _i < _len; _i++) {
          arr = arrs[_i];
          _results.push(escapeRow(arr));
        }
        return _results;
      })();
      return arrs.join('\n');
    };
  });

}).call(this);
