// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'handsontable', 'csvparse', 'bootstrap'], function($) {
    var a;
    a = function(csvdata) {
      var data, tab;
      data = $.csv.toArrays(csvdata);
      $('#test-div').show();
      $('#test-div').handsontable({
        data: data.slice(1),
        colHeaders: data[0],
        colWidths: [55, 80, 80, 80, 80, 80, 80],
        rowHeaders: true,
        minSpareRows: 1,
        stretchH: 'all',
        columnSorting: true,
        contextMenu: true
      });
      tab = $('#test-div').handsontable('getInstance');
      tab.addHook('afterCreateCol', function(colIndex) {
        var headers;
        headers = tab.getColHeader();
        $("#colNameInput").val('class');
        $("#colNameModal").modal('show');
        return $('.nameCol').bind("click", function(e) {
          var name;
          name = $("#colNameInput").val();
          headers[colIndex] = name;
          return $('#test-div').handsontable({
            colHeaders: headers
          });
        });
      });
      return $('#test-div').addClass('table table-hover');
    };
    return a;
  });

}).call(this);
