// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'handsontable', 'csvparse'], function($) {
    var a;
    a = function(csvdata) {
      var data;
      data = $.csv.toArrays(csvdata);
      $('#test-div').show();
      $('#test-div').handsontable({
        data: data.slice(1),
        colHeaders: data[0],
        colWidths: [55, 80, 80, 80, 80, 80, 80],
        rowHeaders: true,
        minSpareRows: 1,
        stretchH: 'all',
        columnSorting: true,
        contextMenu: true
      });
      return $('#test-div').addClass('table table-hover');
    };
    return a;
  });

}).call(this);
