// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'alert', 'csv/arr2csv'], function($, alert, arr2csv) {
    return function($el) {
      var arr, csvdata, data, header, table;
      table = $el.data('handsontable');
      console.log(table);
      if (table != null) {
        header = table.getSettings().colHeaders;
        data = table.getData();
        data.unshift(header);
        data = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            arr = data[_i];
            if (arr[0] != null) {
              _results.push(arr);
            }
          }
          return _results;
        })();
        csvdata = arr2csv(data);
        return csvdata;
      } else {
        return false;
      }
    };
  });

}).call(this);
