// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var a;
    a = function() {
      if (window.File && window.FileReader && window.FileList && window.Blob) {
        return true;
      } else {
        document.writeln('The HTML5 APIs used in this form are only available in the following browsers:<br />');
        document.writeln(' - Google Chrome: 13.0 or later<br />');
        document.writeln(' - Mozilla Firefox: 6.0 or later<br />');
        document.writeln(' - Internet Explorer: Not supported (partial support expected in 10.0)<br />');
        document.writeln(' - Safari: Not supported<br />');
        document.writeln(' - Opera: Not supported');
        return false;
      }
    };
    return a;
  });

}).call(this);
