// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return function(target, callback) {
      var file, files, reader;
      files = target.files != null ? target.files : target[0].files;
      file = files[0];
      reader = new FileReader();
      reader.readAsText(file);
      reader.onload = function(event) {
        var csv;
        csv = event.target.result;
        return callback(csv);
      };
      return reader.onerror = function() {
        return alert('Unable to read ' + file.fileName);
      };
    };
  });

}).call(this);
