// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return function(evt, callback) {
      var url;
      url = 'data/test2.csv';
      return $.ajax(url).done(callback).fail(function() {
        return console.log("Ahh");
      });
    };
  });

}).call(this);
