// Generated by CoffeeScript 1.6.3
(function() {
  define(['csv/table2csv', 'file/loadRemoteFile', 'csv/csv2table'], function(table2csv, loadRemoteFile, csv2table) {
    return function($el, $tablediv, append) {
      var callback;
      if (append == null) {
        append = false;
      }
      if (append) {
        callback = function(data) {
          var oldData;
          console.log(data);
          oldData = table2csv($tablediv);
          if (oldData) {
            data = data.split(/\r\n|\n|\r/gm).slice(1);
            data = data.join('\n');
            console.log(oldData);
            data = "" + oldData + "\n" + data;
            console.log(data);
          }
          return csv2table(data);
        };
      } else {
        callback = function(data) {
          return csv2table(data);
        };
      }
      return $el.bind('click', function(e) {
        return loadRemoteFile(e, callback);
      });
    };
  });

}).call(this);
